import type { NextPage } from 'next'
import Head from 'next/head'
import SidebarMenu from '../components/sidebarMenu'
import { Container } from 'semantic-ui-react'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Max Arvid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SidebarMenu>
          <Container fluid>
            <h1 data-cy="greeting">
              Hejsan Världen!
            </h1>
          </Container>
        </SidebarMenu>
      </main>
    </>
  )
}

export default Home
